### ISSUE TITLE
Delay on Spinner loading first time

### ISSUE THREAD

**Issue by ushinnary** [KeatoonMask/SwiftUI-Animation#1]
Hello, i had the same issue like a user in comments on your Medium guide's page.
So the problem is that on first load the spinner had animation delay of 3-4s before displaying animation.
My solution was to insert `self.animateSpinners()` in `.onAppear()` one more time so it fires instantly and then get repeated by your Timer.

Tested it on Mac Mini M1
Have a good day ^^

**Comment by KeatoonMask** [comment]
@ushinnary Thank you so much for the solution :)
